name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ vars.HOST }}
      DEPLOY_DIRECTORY: /root/apps/transport-engineers

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          ref: backend
          path: backend

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0

      - name: Build go app
        run: |
          cd backend
          go mod download
          go build -o transport-engineers ./cmd/main.go
          cd ..

      - name: Delete old source code
        run: |
          sudo apt-get install -y ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "
            if [ -d '${{ env.DEPLOY_DIRECTORY }}' ]; then
              rm -rf '${{ env.DEPLOY_DIRECTORY }}'
            fi
          "

      - name: Deploy to VM
        run: |
          sudo apt-get install -y rsync
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' \
          --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}

      - name: Remove old systemd service file
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} \
          "rm -f /etc/systemd/system/transport-engineers.service"

      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la ${{ github.workspace }}/deployment
      
      
