name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ vars.HOST }}
      DEPLOY_DIRECTORY: /root/apps/transport-engineers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: backend

      - name: Debug
        run: |
          echo "HOST: $HOST"
          echo "DEPLOY_DIRECTORY: $DEPLOY_DIRECTORY"

      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}